#!/usr/bin/env python3
# Generate a 1024-entry full-period sine LUT in Q12.20 for the firmware.
import math

N = 1024
with open("sintab.h", "w") as f:
    f.write("// Auto-generated by gen_sintab.py -- sin(2*pi*k/%d) in Q12.20\n" % N)
    f.write("static const int sintab[%d] = {\n" % N)
    for k in range(N):
        f.write("  %d,\n" % round(math.sin(2.0 * math.pi * k / N) * (1 << 20)))
    f.write("};\n")
