#!/usr/bin/env python3
# Generate a quarter-wave sine LUT in Q12.20 for the firmware.
# 256 entries span [0, pi/2] (same angular resolution as a 1024-entry full
# period); the full sine is reconstructed by quadrant mirror/negate in main.c.
# Two guard entries so the interpolation's idx+1 is always in bounds.
import math

Q = 256
FXSH = 12   # must match FXSH in main.c (Q20.12)
with open("sintab.h", "w") as f:
    f.write("// Auto-generated by gen_sintab.py -- quarter-wave sin, Q%d.%d\n" % (32 - FXSH, FXSH))
    f.write("#define SINQ %d\n" % Q)
    f.write("static const int sinq[%d] = {\n" % (Q + 2))
    for i in range(Q + 2):
        f.write("  %d,\n" % round(math.sin((i / Q) * (math.pi / 2.0)) * (1 << FXSH)))
    f.write("};\n")
